### ISSUE TITLE
Current code doesn't work with vmware provider (0.6.1)

### ISSUE THREAD

**Issue by alappe** [jordansissel/vagrant-port#2]
I am not sure if it should work, in any case I wanted to report it…

```
% vagrant port 22
/Users/nd/.vagrant.d/gems/gems/vagrant-port-0.0.2/lib/vagrant-port/command.rb:26:in `block in execute': undefined method `read_forwarded_ports' for #<HashiCorp::VagrantVMwarefusion::Driver::Fusion:0x00000100d1b338> (NoMethodError)
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:180:in `each'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
from /Users/nd/.vagrant.d/gems/gems/vagrant-port-0.0.2/lib/vagrant-port/command.rb:25:in `execute'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/cli.rb:46:in `execute'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/environment.rb:467:in `cli'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/bin/vagrant:84:in `<top (required)>'
from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
%
```

**Comment by jordansissel** [comment]
Not sure what the issue was, sorry for the delay also.

Vagrant 1.8 has 'vagrant port' built-in now. Yay! I'll close this in favor of Vagrant 1.8's feature. :)
https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#180-december-21-2015
